# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
np.__version__

'2.2.1'

2) Создать нулевой вектор размера 10

In [2]:
zero_array = np.zeros(10)

3) Создать вектор заполненный 7-ами размера 7

In [3]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
np.arange(10, 100+1, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [6]:
reversed_ = np.random.rand(10)[::-1]

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [7]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [8]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [10]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, np.arange(1, 5))
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [11]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
random_matrix = np.random.rand(10, 10)
means = np.mean(random_matrix, axis=1)
ans = random_matrix - means[:, np.newaxis]
ans

array([[ 0.55282203, -0.09267198, -0.07581995,  0.46252796, -0.28486933,
        -0.2584318 , -0.38080647,  0.04459033,  0.19164142, -0.15898222],
       [ 0.22683444, -0.1410149 , -0.06931935,  0.35925724, -0.15402401,
        -0.42559289,  0.50664743, -0.37882375, -0.19202364,  0.26805943],
       [ 0.05542852,  0.13719085,  0.00876351, -0.1686684 , -0.18524138,
        -0.02346703,  0.16543483, -0.19499451,  0.14728648,  0.05826712],
       [-0.43155241,  0.3478376 ,  0.3652694 , -0.41798554,  0.03700844,
        -0.08395051,  0.09935012,  0.34424439, -0.34503537,  0.08481388],
       [-0.09906415,  0.32533203,  0.29089029,  0.14098786, -0.05580969,
        -0.41073854, -0.05570333, -0.23008149,  0.16518964, -0.07100262],
       [ 0.32618564, -0.42988337,  0.25964723,  0.15755703, -0.21423437,
        -0.26035211,  0.3770427 , -0.10728598, -0.35460356,  0.24592679],
       [-0.27556149,  0.53469736, -0.04025579, -0.25488757, -0.25672405,
         0.62315602, -0.12979986,  0.00990709

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [14]:
random_matrix = np.random.rand(10, 10)
medians = np.median(random_matrix, axis=1)
ans = random_matrix - medians[:, np.newaxis]
ans

array([[ 0.04073681, -0.15610631,  0.20423351, -0.0393225 , -0.28827855,
        -0.58673344, -0.25472406,  0.07611052,  0.35367875,  0.0393225 ],
       [-0.14135963,  0.25737607, -0.0647722 ,  0.59740932,  0.23153767,
         0.32156903,  0.0647722 , -0.23431539, -0.09035492, -0.13537571],
       [-0.2939336 , -0.27860588,  0.07728423,  0.21834246,  0.02224225,
        -0.32290642, -0.02224225, -0.42987349,  0.1068169 ,  0.36083968],
       [-0.21990455, -0.09874022,  0.34972563,  0.05414762, -0.07107098,
        -0.05051299, -0.53877414,  0.18389379,  0.1758671 ,  0.05051299],
       [ 0.19884439,  0.2932346 ,  0.27135913, -0.51514979,  0.03866492,
         0.18655976, -0.44145205, -0.03866492, -0.51459522, -0.43180697],
       [-0.30217856,  0.46597826, -0.00795562,  0.52642186, -0.01106922,
         0.13103005, -0.15038225,  0.00450844,  0.46500707, -0.00450844],
       [ 0.0260302 ,  0.10564741, -0.07788136, -0.04821768, -0.26599765,
        -0.0260302 , -0.21083751,  0.4720614 

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [15]:
random_matrix = np.random.rand(5, 5)
row_max = np.max(random_matrix, axis=1)
row_min = np.min(random_matrix, axis=1)
result_matrix = np.hstack((random_matrix, row_max[:, np.newaxis], row_min[:, np.newaxis]))

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [28]:
vec = np.arange(1, 51)

odd_numbers = vec[vec % 2 == 1] 
even_numbers = vec[vec % 2 == 0] 

matrix_odd = odd_numbers.reshape(5, 5)
matrix_even = even_numbers.reshape(5, 5)

product_matrix = np.dot(matrix_odd, matrix_even)

try:
    inverse_matrix = np.linalg.inv(product_matrix)
    print("Обратная матрица произведения:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Произведение матриц вырождено, обратная матрица не существует.")

Произведение матриц вырождено, обратная матрица не существует.


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [33]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
